; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:lilygo-t-dongel-s3]
board = lilygo-t-dongel-s3
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-dongel-s3>
board_build.arduino.memory_type = qio_qspi
board_build.partitions = custom_16Mb.csv
build_flags =
	${env.build_flags}
	-Iboards/lilygo-t-dongel-s3
	-Os
	-DCORE_DEBUG_LEVEL=1
	-DRF_TX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'
	-DRF_RX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'
	-DIR_TX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'
	-DIR_RX_PINS='{{"Pin 43", 43}, {"Pin 44", 44}}'
	;Have buzzer
	-D USE_HSPI_PORT=1
	-DUSE_SD_MMC=1
	-DDEVICE_NAME='"LilyGo T-Dongle S3"'

lib_deps =
	    ${env.lib_deps}

