; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:S3_supermini_madara]
board = S3_supermini_madara
build_src_filter =${env.build_src_filter} +<../boards/S3_supermini_madara>
board_build.arduino.memory_type = qio_qspi
board_build.partitions = custom_4Mb_fullv2.csv
build_flags =
	${env.build_flags}
	-Iboards/S3_supermini_madara
	-Os
	-DCORE_DEBUG_LEVEL=1
	-DRF_TX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DRF_RX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}}'
	-DIR_TX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}, {"Pin 14", 14}, {"Pin 15", 15}}'
	-DIR_RX_PINS='{{"Pin 4", 4}, {"Pin 5", 5}, {"Pin 14", 14}, {"Pin 15", 15}}'
	;Have buzzer
	-DBUZZ_PIN=47
	-D USE_HSPI_PORT=1
	-DDEVICE_NAME='"Madara Board"'

lib_deps =
	    ${env.lib_deps}
